apiVersion: batch.appservice.com/v1
kind: AppService
metadata:
  name: nginx-app
  # 修改成你的namespace
  namespace: caas-system
spec:
  image: nginx
  replicas: 1
  ports:
    - name: http
      port: 80
      targetPort: 80
