# permissions for end users to edit appservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller-demo
    app.kubernetes.io/managed-by: kustomize
  name: appservice-editor-role
rules:
- apiGroups:
  - batch.appservice.com
  resources:
  - appservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.appservice.com
  resources:
  - appservices/status
  verbs:
  - get
